### ISSUE TITLE
Explanation

### ISSUE THREAD

**Issue by alexanderremmerie** [ndeineko/TI-MultiView-data-recovery#1]
Hi,
This i a really cool bug. Can you explain what's going on in the memory while performing the bug?
Is there a buffer overflow somewhere? Thank you for your answer.

**Comment by ndeineko** [comment]
Hello @alexanderremmerie

There are actually multiple different bugs used in the procedure (there are also other bugs of this calculator that have no use here), I can give a general explanation of what is happening in the memory, but I don't know what causes the bugs at the instruction level.

### Memory

The data memory layout is made of fixed size "zones". Some examples:
- "Home screen" entries (first zone, at offset 0)
- "Data editor" entries (accessed with `data` key)
- "Constant" value/function (accessed with `2nd` `÷`)
- "Function table" function (accessed with `table` key)

To store the symbols inside most parts of the data memory (examples: "Home screen", "Constant" and "Function table"), the calculator uses a 1 byte (8 bits or rather two times 4 bits) "alphabet", where one symbol uses one byte.

Some examples:

Byte value (decimal) | Byte value (hex) | Symbol
--- | --- | ---
1 | 01 | `(`
2 | 02 | `,`
3 | 03 | `+`
4 | 04 | `*`
5 | 05 | ` nCr `
25 | 19 | `iPart(`
30 | 1E | `1`
42 | 2A | `log(`
46 | 2E | `2`
47 | 2F | `minX`
62 | 3E | `3`
75 | 4B | `tan(`
105 | 69 | `lcm(`
121 | 79 | `gcd(`
137 | 89 | `remainder(`
143 | 8F | `Clear L3`
157 | 9D | `1-Var Stats`
188 | BC | `π`

Some of them are usable symbols (or functions) that are accessible trough keys/menus (like `+`, `*`, ` nCr `, `tan(`) or not (like `iPart(`, `lcm(`, `gcd(` or `remainder(` : those ones are accessible with keys/menus in older/different models of TI calculators but they do work on the TI-30X B/S MultiView).
Some are used in the menus: they will produce unexpected results if put inside a calculation (like `Clear L3` or `1-Var Stats`).
Some others (not represented here) need multiple bytes because the MathPrint mode stores textbook-style symbols (like square root, exponent, ...) with multiple bytes. For example, square root of ... is (in decimal): 74, ..., 33.

To store the entries inside the "Data editor", the calculator uses another system because those entries are not stored as a calculation but as a number:

- One byte indicate with a bitmask if the number is special, like a negative number, a fraction or a multiple of `π`.
- 6 bytes (or 12 times 4 bits) contain the fraction or number with a 16 characters (4 bits) alphabet for the 10 digits (the other 6 characters are symbols, arrow, spaces, ...).
- One byte stores the exponent.

Right now, I explained how the symbols are stored, but to distinguish the entries from each others, they need to be inside a structure:
- In the "Data editor", this is simple: every cell of the table is at a fixed position and uses exactly 8 bytes. The calculator also stores the number of rows of each column somewhere.
- For the "Home screen" entries, this is different:
	- The first byte indicates the length of the entry (including the length (1) of this byte itself and the length (2 or 4) of the metadata). A length of 0 means there is no next entry in memory (end of the "list"). A length of 255 for a result indicate an `Error` and does not contain other metadata or data.
	- The next 2 (for inputs) or 4 (for result) bytes are the metadata bytes: they contain information about the height/width of the entry on screen and (for the results only) the position on screen.
	- Then there are the symbols (explained previously) making this entry.

For example, if you type square root of 121 on the home screen and press `enter`, this is what the data memory will look like (in decimal):

| **Offset** | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | ... |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| **Value** | 7 | 84 | 2 | 12 | 8 | 30 | 30 | 8 | 24 | 10 | 74 | 30 | 46 | 30 | 33 | 0 | ... |

Details:

Values | Explanation
--- | ---
7 | size of result (1 + 2 + 2 + 2 = 7)
84, 2 | on screen result position
12, 8 | on screen result dimensions
30 | number `1`
30 | number `1`
8 | size of input
24, 10 | on screen input dimensions
74 | start of square root symbol
30 | number `1`
46 | number `2`
30 | number `1`
33 | end of square root symbol
0 | entry of size 0 = end of entries list

It you enter it twice, this sequence (without the zero at the end) will simply appear twice with the zero at the end.

To reset the "Data editor" values, the calculator sets the length of the columns to 0.
The way the calculator resets the "Home screen" entries is by setting the very first byte to 0. That way, the "list" is broken but the entries are still in memory as long as they are not erased by new entries.

For example, if you press reset now, this is what the memory will look like:

| **Offset** | 0 | 1 | 2 | 3 | 4 | 5 | 6 | ... |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| **Value** | 0 | 84 | 2 | 12 | 8 | 30 | 30 | ... |

### Bugs

#### First Bug

The first bug is what I call the "half-delete". Normally, when an input or result is deleted, the (respectively) result or input associated with it is also deleted.
This bug will delete only the most recent entry in memory: either a result or an input.

Here are 2 variants/examples that will trigger it (assuming the cursor in on the home screen):

`data` `0` `enter` `▶` `sto▸` `data` `enter` `enter` `sto▸` `clear` `clear` `2nd` `mode`
or
`data` `3` `enter` `▶` `sto▸` `data` `1` `enter` `sto▸` `clear` `clear` `clear` `clear` `clear`

After doing it once (or an odd number of times), the calculator will interpret the inputs as the results and the results as the inputs. 
Since the results use 2 more bytes of metadata, the inputs (displayed as results) will be truncated of their first 2 bytes (those bytes will be interpreted as the dimensions by the calculator). And the results (displayed as inputs) will gain 2 bytes that corresponded to their original dimensions on screen. Those bytes will be interpreted as symbols by the calculator.

This allows generating some specific symbols. Obviously, if a MathPrint symbol is not complete (like 74, ... without 33 ever) this will produce some interesting bugs, undefined behaviours or freezes.

#### Second bug:

After this sequence of operations:
- Typing one character (let's call it the offset, we'll see later why) that will give an error when `enter` is pressed; in this example, this is the `.` character (other examples: `+`, `-`, ...)
- Pressing `enter`
- Pressing the exponentiation key (`^`) to get `.` to the power of `a square with a dotted border`
- Pressing `enter`
- Performing the "half-delete" bug

The data memory looks like this (in decimal):

| **Offset** | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | ... |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| **Value** | 7 | 12 | 10 | 18 | 7 | 51 | 113 | 255 | 4 | 6 | 8 | 18 | 0 | 0 | 255 | 4 | 6 | 8 | 18 | 0 | ... |

Details:

Values | Explanation
--- | ---
7 | size of entry
12, 10 | dimensions of entry on screen
18 | `.`
7 | start of exponent symbol
51 | square with a dotted border
113 | end of exponent symbol
225 | size of entry, 255 = Error, this is the result of `.` `enter`
4 | size of entry
6, 8 | dimensions of entry on screen
18 | `.`
0 | entry of size 0 = end of entries list
0, 255, 4, 6, 8, 18, 0 | inaccessible leftover copy of result `Error` and input `.` because the "half-delete" moved the list to the left after one entry was deleted.

But since the "half-delete" only deleted one entry, we now have 3 entries in memory, with the most recent one being interpreted as a result, so this is how the calculator sees it:

Values | Explanation
--- | ---
7 | size of entry
12, 10 | position of entry on screen
18, 7 | dimensions of entry on screen
51 | square with a dotted border
113 | end of exponent symbol (which has no start anymore ...)

So we now have extracted an incomplete MathPrint symbol that appears as a square with a dotted border.

We can now select this entry with `▲` and paste it on the editable line (bottom line) of the home by pressing `enter` once.
The editable line will look like this in the *Work RAM* (in decimal): 51, 133.
Now if we press `◀`, and paste the entry again at that position, the editable line contains: 51, 133, 133. It looks like one of the 51 got overwritten.
Now, if we press `delete`, this will trigger the "second bug" and the memory will suddenly look like this (in decimal):

| **Offset** | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 20 | 21 | 22 | 23 | 24 | 25 | 26 | 27 | ... |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| **Value** | 6 | 90 | 0 | 6 | 8 | 14 | 3 | 0 | 8 | 18 | 7 | 51 | 113 | 255 | 4 | 6 | 8 | 18 | 0 | 0 | 255 | 4 | 6 | 8 | 18 | 0 | ... | ?? | ... |

What causes this exactly is unclear to me but the result is that the first 3 bytes (7, 12, 10) are replaced by (6, 90, 0, 6, 8, 14, 3, 0, 8) and the next bytes are moved to the right.
The memory is now interpreted by the calculator as:
- One entry of size 6
- One entry of size 3
- One entry of size 18 
- The rest depends on what value is present at the byte with offset 27 (= 6 + 3 + 18).

This has an interesting consequence: the symbol `.` that has a decimal byte representation of 18 is now interpreted as the size on an entry (at offset 9).
So, by knowing the position of the inaccessible entries in memory, it it possible to find the character/symbol (in this example `.`) corresponding to the right offset (in this example 18) and, with this technique, set the byte at offset 9 to point to the next entry and then remove the few garbage entries (with deletes or half-deletes depending on the number of entries).

In the full procedure, I simplified the calculation of the *size* value a bit, as it differs from the actual offset by a constant number.

#### Third bug

A large part of the procedure is composed of tricks to set the value of the byte at offset 9 to the right offset, but there is also another bug worth mentioning to reach this goal in some specific cases:

Normally, in the "Data editor", there are only 42 rows. But there the is a way to access rows 43 and higher.
This is not very useful in everyday use as this additional space comes from somewhere: the values overflow on the next columns (for example: column 1 from row 43 to 82 corresponds to column 2 from row 1 to 42) or on another memory location (for example: column 3, row 61 will write inside the "Constant" value/function ordinarily accessible with `2nd` `÷`). Technically, this is a buffer overflow.

Here is one way to get more than 42 rows (assuming the cursor is on the home screen and the data editor is empty):

- Press `data`.
- (40 times) Press `0` `enter`.
- At this point, the bottom of the screen should show `L1(41)=    `. If it's not the case, insert or delete the right amount of cells to get 40 lines of zeros and go to row 41.
- Press `▶`
- Press `sto▸` `data` `enter` `enter` `▲` `0` `enter`
- Press `◀` `0` `enter` `0` `enter` `enter` `0` `enter`

This is useful in some specific cases (when *size* is equal to 21 or 22), in order to get a specific character thanks to the different encoding used by the "Data editor" compared to the "Constant" value/function (`2nd` `÷`).

The 43rd row is also used when the most recent entry in the memory is too small and would be overwritten by the recovery procedure: when this row is reached, it is possible to move the whole "Home screen" memory by an offset of 8 by simply pressing `2nd` `delete` on the 43rd row.

I hope this answers your questions.

**Comment by alexanderremmerie** [comment]
Thank you for this very detailed explanation.
Would it be possible to write data to memory so that the calculator interprets the data as code (like assembler) and execute your own code on the calculator? 
For example, is it possible to make a snake game and then write it to memory so that the calculator executes the code (if possible, without deleting the authentic code)?

**Comment by ndeineko** [comment]
I don't think this is possible.
Only *Work RAM* (small, fast) and *Data RAM* (bigger, slower) are both modifiable and big enough to store a (very small) program but, unfortunately, the processor cannot directly execute code stored in RAM. The executable code is stored in ROM, which is not modifiable (at least without external tools).
